"""empty message

Revision ID: 510489cd22f2
Revises: 70e349313ff4
Create Date: 2022-09-16 18:31:04.229261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510489cd22f2'
down_revision = '70e349313ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permission', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permission', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
